title: "Sharon Alexander"
description: "Portfolio showcasing my data science projects, skills, and experience."
logo: assets/head-shot-circle.png  # Uncomment and set path if you have a logo
show_downloads: false #https://avatars.githubusercontent.com/u/30108439?v=

# Choose a supported Jekyll theme (see https://pages.github.com/themes/)
theme: jekyll-theme-minimal

# Social links (optional)
github_username: sharona1ex
linkedin_username: sharona1ex
email: sharonalexander2596@gmail.com

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Build settings (optional, for advanced users)
# markdown: kramdown
# plugins:
#   - jekyll-feed
